spring:
  application:
    name: aihelpdesk
  datasource:
    url: jdbc:mysql://localhost:3306/aihelpdesk?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
app:
  jwt:
    secret: "12345678901234567890123456789012"
    expire-millis: 7200000
  upload:
    document-dir: uploads/documents
  storage:
    type: minio
    minio:
      endpoint: http://localhost:9000
      access-key: minioadmin
      secret-key: minioadmin
      bucket: aihelpdesk
      secure: false
